# This code shows some simple data cleaning procedures

Note that, in order to make the code simple, many details (sometimes quite important) are not considered.

The input file used as example is the one generated in the TwitterFriends example


## Main items introduced
1. Simple data cleaning strategies
2. Reading and writing dataframes from CSV files
  * pd.read_csv
  * df.to_csv
3. Exploring dataframes
  * df - shows beginning and end of table
  * df.head() - shows the first five rows
  * df\[&lt;column_name&gt;\] - shows the column &lt;column_name&gt;
  * df\[&lt;column_name&gt;\]\[&lt;row number&gt;\] - shows the content of the cell
  * df.dtypes - shows the type of each column
  * df\[&lt;column_name&gt;\].unique() - shows unique values of the items in the column &lt;column_name&gt;
  * df\[df.&lt;column_name&gt; == '&lt;value&gt;'\] - returns all rows that have the value &lt;value&gt; in the column &lt;column_name&gt;. Note that the condition in the square bracket may be complex, see for example code line 21
4. Manipulating dataframes
  * df.copy() - creates a copy of the datframe
  * df.dropna(PARAM) - rows or columns based on NaN (no value assigned)
  * df.drop(PARAM) - drop rows or columns
  * df.replace(PARAM) - replaces the content of cells
  * df\['&lt;column_name&gt;'\]\[&lt;row number&gt;\] = '&lt;value&gt;' - assignes the value &lt;value&gt; to the cell
5. Simple regular expressions

In [1]:
import pandas as pd
import numpy as np

In [2]:
# read the file generated with the twitter API in a data frame and show first five records
df = pd.read_csv('dataFromTwitter.txt', sep='\t')
df.head()

,screen_name,name,followers_count,location,status
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC",Thanks for joining! https://t.co/YNNjGghUxR
1,jessebwatters,Jesse Watters,410410,NaN,RT @FNC_Ladies_Rule: üçæüéâFox News is No. 1 Basic...
2,https://t.co/cbHoqt3QTG https://t.co/ODX77‚Ä¶,NaN,NaN,NaN,NaN
3,WhiteHouse,The White House,15327283,"Washington, D.C.","Lt. Gen. (Ret) Keith Kellogg: ""Trump as Comman..."
4,Scavino45,Dan Scavino Jr.,148667,@Twitter @DanScavino,'It is time to heal the wounds that have divid...

In [3]:
# show the entire data frame - note the summary (number of row and columns) at the end
df

,screen_name,name,followers_count,location,status
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC",Thanks for joining! https://t.co/YNNjGghUxR
1,jessebwatters,Jesse Watters,410410,NaN,RT @FNC_Ladies_Rule: üçæüéâFox News is No. 1 Basic...
2,https://t.co/cbHoqt3QTG https://t.co/ODX77‚Ä¶,NaN,NaN,NaN,NaN
3,WhiteHouse,The White House,15327283,"Washington, D.C.","Lt. Gen. (Ret) Keith Kellogg: ""Trump as Comman..."
4,Scavino45,Dan Scavino Jr.,148667,@Twitter @DanScavino,'It is time to heal the wounds that have divid...
5,KellyannePolls,Kellyanne Conway,1664393,"Washington, DC",Important read: Gen. Kellogg combines personal...
6,Reince,Reince Priebus,941927,"Kenosha, WI and Washington, DC","Thanks to @POTUS, Foxconn, @ScottWalker, @PRya..."
7,‚úîÔ∏è$10B investment,NaN,NaN,NaN,NaN
8,‚úîÔ∏è13K jobs,NaN,NaN,NaN,NaN
9,‚úîÔ∏è #MadeInAmerica,NaN,NaN,NaN,NaN
10,RealRomaDowney,Roma Downey,192126,Malibu,Kindness matters ü¶ã #bekind https://t.co/telXo6...
11,Trump,Trump Organization,254702,"New York, NY",Brighten up your mornings in the Windy City wi...
12,TrumpGolf,Trump Golf,66333,NaN,Rejoice in the ride and leave the rest to us! ...
13,TiffanyATrump,Tiffany Ariana Trump,429759,NaN,üåñüåóüåòüåëüåíüåì#SolarEclipse2017 @ Lijst van bekende me...
14,IngrahamAngle,Laura Ingraham,1664852,DC,"Is it ""normalcy"" to govern by by ""continuing r..."
15,mike_pence,Mike Pence,2257112,NaN,"Since day 1, @realDonaldTrump has been fightin..."
16,TeamTrump,Official Team Trump,742514,USA,RT @WhiteHouse: Watch LIVE as President Trump ...
17,DRUDGE_REPORT,DRUDGE REPORT,1319753,US,Now ISIS threatens Rome... https://t.co/ZOjKSk...
18,MrsVanessaTrump,Vanessa Trump,215576,NaN,RT @DonaldJTrumpJr: The most interesting measu...
19,LaraLeaTrump,Lara Trump,301998,New York City,"RT @JennaBrowder: ""He truly is a man of God"" -..."
20,seanhannity,Sean Hannity,2754923,NYC,Health warning to protestors! Do not fight wi...
21,foxnation,Fox Nation,393715,NaN,#Obama's Bureaucrats Are Still Running the Tit...
22,CLewandowski_,Corey R. Lewandowski,285315,"Washington, DC",CFPB chief Cordray thinks he‚Äôs above the law ‚Äì...
23,AnnCoulter,Ann Coulter,1662294,Los Angeles/NYC,RT @immigrant4trump: Camping World tells Trump...
24,DiamondandSilk,Diamond and Silk¬Æ,382889,United States,When will the Fake News start to realize that ...
25,KatrinaCampins,KATRINA CAMPINS,307559,Peace Within,Babymoon Vacation! Very fitting given the Scol...
26,KatrinaPierson,Katrina Pierson,339906,"Washington, DC",RT @realDonaldTrump: If Republican Senate does...
27,MichaelCohen212,Michael Cohen,257489,New York,RT @PressSec: .@POTUS: ‚ÄúIt is time to heal the...
28,foxandfriends,FOX & friends,1012750,New York City,Join us tomorrow on the plaza! Country star @J...
29,MELANIATRUMP,MELANIA TRUMP,892678,New York City,üá∫üá∏ https://t.co/CcV2HZ1roV
...,...,...,...,...,...
74,LaraLeaTrump,Lara Trump,492595,New York City,RT @EricTrump: I‚Äôll be on ‚Å¶@SeanHannity‚Å© with ...
75,seanhannity,Sean Hannity,3928199,NYC,WATCH BELOW: Entire Congress ERUPTS in Biparti...
76,CLewandowski_,Corey R. Lewandowski,388884,"Washington, DC",President‚Äôs State of the Union promises an¬†Ame...
77,DiamondandSilk,Diamond and Silk¬Æ,1010717,United States,RT @SteveKingIA: Some shots from the #StateOfT...
78,KatrinaCampins,KATRINA CAMPINS,273821,Peace Within,South Florida Mansion Sales Surge as Tax Exile...
79,KatrinaPierson,Katrina Pierson,443386,"Washington, DC",RT @realDonaldTrump: #SOTU
80,https://t.co/kL6SoClx4K,NaN,NaN,NaN,NaN
81,foxandfriends,FOX & friends,1335507,New York City,After the Show Show: @jrodfromoz explains what...
82,MELANIATRUMP,MELANIA TRUMP,1064983,New York City,RT @FLOTUS: This has been a year filled with m...
83,GeraldoRivera,Geraldo Rivera,265232,New York City,For all her admirable qualities: compassionate...
84,ericbolling,Eric Bollingüá∫üá∏,1080806,NYC,CBS Evening News
85,@CBSEveningNews,NaN,NaN,NaN,NaN
86,CBS NEWS POLL: 76% of viewers approved of what...,NaN,NaN,NaN,NaN
87,MarkBurnettTV,Mark Burnett,219525,Los Angeles,RT @EcoChallengeMGM: Team Registration is now ...
88,garyplayer,Gary Player,393259,South Africa,RT @jacknicklaus: Feats of strength by my ‚Äúold...
89,VinceMcMahon,Vince McMahon,2197623,"Greenwich, Conn.","Unflinching, uncompromising and unmistakably T..."
90,DanScavino,Dan Scavino,507539,"Washington, DC",25 years of being on the links with @realDonal...
91,TrumpDoral,Trump National Doral,87502,"Miami, Florida",@JoeyBaboots @RiggsBarstool @DonaldJTrumpJr @E...
92,TrumpCharlotte,Trump Charlotte,69155,"Charlotte, NC","We are right there with you, Eric and will con..."
93,TrumpLasVegas,Trump Vegas Hotel,126917,Las Vegas,Life is cool by the pool... but it's even cool...
94,TrumpChicago,Trump Hotel Chicago,94208,"Chicago, IL",RT @EricTrump: Record-breaking cold temperatur...
95,TrumpGolfDC,Trump Washington DC,98794,"Sterling, VA",Trump National DC offers a beautiful ballroom ...
96,TrumpGolfLA,Trump Los Angeles,81502,"Los Angeles, CA",Make sure this Sunday will be truly Super! Vis...
97,EricTrump,Eric Trump,2329040,NaN,I‚Äôll be on ‚Å¶@SeanHannity‚Å© with ‚Å¶@LaraLeaTrump‚Å©...
98,BillOReilly,Bill O'Reilly,2967067,NaN,Americans watching last night's #SOTU saw a fa...
99,greta,Greta Van Susteren,1201546,Washington,RT @AMAZlNGNATURE: He likes an apple üçéü¶î
100,üìΩÔ∏èig: hedgehog_azuki https://t.co/96alP2JT13,NaN,NaN,NaN,NaN
101,piersmorgan,Piers Morgan,6535363,"London, Newick, LA.",They can't afford me.. https://t.co/Ud3cjo2Ck3
102,DonaldJTrumpJr,Donald Trump Jr.,3300797,NaN,I guess she doesn‚Äôt want to put an end to sex ...
103,IvankaTrump,Ivanka Trump,6159430,"Washington, DC",RT @USAIDMBekkering: Thanks to @IvankaTrump &a...

In [4]:
# each column can be accessed by providing its name
df['name']

0            Tucker Carlson
1             Jesse Watters
2                       NaN
3           The White House
4           Dan Scavino Jr.
5          Kellyanne Conway
6            Reince Priebus
7                       NaN
8                       NaN
9                       NaN
10              Roma Downey
11       Trump Organization
12               Trump Golf
13     Tiffany Ariana Trump
14           Laura Ingraham
15               Mike Pence
16      Official Team Trump
17            DRUDGE REPORT
18            Vanessa Trump
19               Lara Trump
20             Sean Hannity
21               Fox Nation
22     Corey R. Lewandowski
23              Ann Coulter
24        Diamond and Silk¬Æ
25          KATRINA CAMPINS
26          Katrina Pierson
27            Michael Cohen
28            FOX & friends
29            MELANIA TRUMP
               ...
74               Lara Trump
75             Sean Hannity
76     Corey R. Lewandowski
77        Diamond and Silk¬Æ
78          KATRINA CAMPINS
79          Katrina Pierson
80                      NaN
81            FOX & friends
82            MELANIA TRUMP
83           Geraldo Rivera
84           Eric Bollingüá∫üá∏
85                      NaN
86                      NaN
87             Mark Burnett
88              Gary Player
89            Vince McMahon
90              Dan Scavino
91     Trump National Doral
92          Trump Charlotte
93        Trump Vegas Hotel
94      Trump Hotel Chicago
95      Trump Washington DC
96        Trump Los Angeles
97               Eric Trump
98            Bill O'Reilly
99       Greta Van Susteren
100                     NaN
101            Piers Morgan
102        Donald Trump Jr.
103            Ivanka Trump
Name: name, Length: 104, dtype: object

In [5]:
# each element can be accessed by providing the name of the column and the row number
df['name'][96]

'Trump Los Angeles'

In [6]:
# Every column has a type (in this case all columns contain objects)
df.dtypes

screen_name        object
name               object
followers_count    object
location           object
status             object
dtype: object

#### Do exercises 1,2 and 3 in the CleaningDataExercises notebook

In [7]:
# make a copy of the data frame
df1 = df.copy()
# dropna allows to drop lines (or columns if axis=1) that contain non assigned values (NaN)
# in this case I have indicated to drop the lines that have NaN in the location column (subset=['location'])
df2 = df1.dropna(subset=['location'], axis=0, how='any')

In [8]:
df2

,screen_name,name,followers_count,location,status
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC",Thanks for joining! https://t.co/YNNjGghUxR
3,WhiteHouse,The White House,15327283,"Washington, D.C.","Lt. Gen. (Ret) Keith Kellogg: ""Trump as Comman..."
4,Scavino45,Dan Scavino Jr.,148667,@Twitter @DanScavino,'It is time to heal the wounds that have divid...
5,KellyannePolls,Kellyanne Conway,1664393,"Washington, DC",Important read: Gen. Kellogg combines personal...
6,Reince,Reince Priebus,941927,"Kenosha, WI and Washington, DC","Thanks to @POTUS, Foxconn, @ScottWalker, @PRya..."
10,RealRomaDowney,Roma Downey,192126,Malibu,Kindness matters ü¶ã #bekind https://t.co/telXo6...
11,Trump,Trump Organization,254702,"New York, NY",Brighten up your mornings in the Windy City wi...
14,IngrahamAngle,Laura Ingraham,1664852,DC,"Is it ""normalcy"" to govern by by ""continuing r..."
16,TeamTrump,Official Team Trump,742514,USA,RT @WhiteHouse: Watch LIVE as President Trump ...
17,DRUDGE_REPORT,DRUDGE REPORT,1319753,US,Now ISIS threatens Rome... https://t.co/ZOjKSk...
19,LaraLeaTrump,Lara Trump,301998,New York City,"RT @JennaBrowder: ""He truly is a man of God"" -..."
20,seanhannity,Sean Hannity,2754923,NYC,Health warning to protestors! Do not fight wi...
22,CLewandowski_,Corey R. Lewandowski,285315,"Washington, DC",CFPB chief Cordray thinks he‚Äôs above the law ‚Äì...
23,AnnCoulter,Ann Coulter,1662294,Los Angeles/NYC,RT @immigrant4trump: Camping World tells Trump...
24,DiamondandSilk,Diamond and Silk¬Æ,382889,United States,When will the Fake News start to realize that ...
25,KatrinaCampins,KATRINA CAMPINS,307559,Peace Within,Babymoon Vacation! Very fitting given the Scol...
26,KatrinaPierson,Katrina Pierson,339906,"Washington, DC",RT @realDonaldTrump: If Republican Senate does...
27,MichaelCohen212,Michael Cohen,257489,New York,RT @PressSec: .@POTUS: ‚ÄúIt is time to heal the...
28,foxandfriends,FOX & friends,1012750,New York City,Join us tomorrow on the plaza! Country star @J...
29,MELANIATRUMP,MELANIA TRUMP,892678,New York City,üá∫üá∏ https://t.co/CcV2HZ1roV
30,GeraldoRivera,Geraldo Rivera,157925,New York City,I'm with @GeorgeForeman &amp; #CharlesBarkley ...
31,ericbolling,Eric Bolling,729649,NYC,I will continue to fight against these false s...
32,MarkBurnettTV,Mark Burnett,193488,Los Angeles,RT @FunderdomeABC: It's all about smart busine...
33,garyplayer,Gary Player,359255,South Africa,#LOVE https://t.co/mN10m0SnK3
34,VinceMcMahon,Vince McMahon,1789522,"Greenwich, Conn.",.@JohnCena continues to inspire countless peop...
36,TrumpWaikiki,Trump Waikiki,48325,"Waikiki, Oahu","Join us for #yoga @ 7:00am Mon, Weds &amp; Fri..."
37,TrumpDoral,Trump National Doral,56443,"Miami, Florida","With fall around the corner, it's time to book..."
38,TrumpCharlotte,Trump Charlotte,38486,"Charlotte, NC",RT @TrumpRealty: 138 Yacht Road; the ideal spa...
39,TrumpLasVegas,Trump Vegas Hotel,99719,Las Vegas,Roasted #salmon with chorizo &amp; navy bean f...
40,TrumpChicago,Trump Hotel Chicago,67529,"Chicago, IL",RT @amybizzarri: Indulge in Summery Spa Treatm...
...,...,...,...,...,...
61,KellyannePolls,Kellyanne Conway,2584390,USAüá∫üá∏,RT @Liz_Cheney: Things my Democrat women colle...
62,Reince,Reince Priebus,934750,"Kenosha, WI and Washington, DC",RT @Reince: @realDonaldTrump Nails it again! ...
63,RealRomaDowney,Roma Downey,238918,"California, USA",@IrishCentral üíõ‚òòÔ∏èüíõ
64,Trump,The Trump Organization,350208,"New York, NY",The American football season might be over but...
67,IngrahamAngle,Laura Ingraham,2581320,DC,"Reading, writing and left-wing activism: ‚ÄúDurh..."
69,TeamTrump,Official Team Trump,956501,USA,"Join President Trump in El Paso, Texas on MONDAY!"
72,DRUDGE_REPORT,DRUDGE REPORT,1403331,US,APPLE scrambles... https://t.co/jEUlOh8L38
74,LaraLeaTrump,Lara Trump,492595,New York City,RT @EricTrump: I‚Äôll be on ‚Å¶@SeanHannity‚Å© with ...
75,seanhannity,Sean Hannity,3928199,NYC,WATCH BELOW: Entire Congress ERUPTS in Biparti...
76,CLewandowski_,Corey R. Lewandowski,388884,"Washington, DC",President‚Äôs State of the Union promises an¬†Ame...
77,DiamondandSilk,Diamond and Silk¬Æ,1010717,United States,RT @SteveKingIA: Some shots from the #StateOfT...
78,KatrinaCampins,KATRINA CAMPINS,273821,Peace Within,South Florida Mansion Sales Surge as Tax Exile...
79,KatrinaPierson,Katrina Pierson,443386,"Washington, DC",RT @realDonaldTrump: #SOTU
81,foxandfriends,FOX & friends,1335507,New York City,After the Show Show: @jrodfromoz explains what...
82,MELANIATRUMP,MELANIA TRUMP,1064983,New York City,RT @FLOTUS: This has been a year filled with m...
83,GeraldoRivera,Geraldo Rivera,265232,New York City,For all her admirable qualities: compassionate...
84,ericbolling,Eric Bollingüá∫üá∏,1080806,NYC,CBS Evening News
87,MarkBurnettTV,Mark Burnett,219525,Los Angeles,RT @EcoChallengeMGM: Team Registration is now ...
88,garyplayer,Gary Player,393259,South Africa,RT @jacknicklaus: Feats of strength by my ‚Äúold...
89,VinceMcMahon,Vince McMahon,2197623,"Greenwich, Conn.","Unflinching, uncompromising and unmistakably T..."
90,DanScavino,Dan Scavino,507539,"Washington, DC",25 years of being on the links with @realDonal...
91,TrumpDoral,Trump National Doral,87502,"Miami, Florida",@JoeyBaboots @RiggsBarstool @DonaldJTrumpJr @E...
92,TrumpCharlotte,Trump Charlotte,69155,"Charlotte, NC","We are right there with you, Eric and will con..."
93,TrumpLasVegas,Trump Vegas Hotel,126917,Las Vegas,Life is cool by the pool... but it's even cool...
94,TrumpChicago,Trump Hotel Chicago,94208,"Chicago, IL",RT @EricTrump: Record-breaking cold temperatur...
95,TrumpGolfDC,Trump Washington DC,98794,"Sterling, VA",Trump National DC offers a beautiful ballroom ...
96,TrumpGolfLA,Trump Los Angeles,81502,"Los Angeles, CA",Make sure this Sunday will be truly Super! Vis...
99,greta,Greta Van Susteren,1201546,Washington,RT @AMAZlNGNATURE: He likes an apple üçéü¶î
101,piersmorgan,Piers Morgan,6535363,"London, Newick, LA.",They can't afford me.. https://t.co/Ud3cjo2Ck3
103,IvankaTrump,Ivanka Trump,6159430,"Washington, DC",RT @USAIDMBekkering: Thanks to @IvankaTrump &a...

In [9]:
# remove the status column
df2.drop(['status'], inplace=True, axis=1)
df2

/opt/tljh/user/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

,screen_name,name,followers_count,location
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC"
3,WhiteHouse,The White House,15327283,"Washington, D.C."
4,Scavino45,Dan Scavino Jr.,148667,@Twitter @DanScavino
5,KellyannePolls,Kellyanne Conway,1664393,"Washington, DC"
6,Reince,Reince Priebus,941927,"Kenosha, WI and Washington, DC"
10,RealRomaDowney,Roma Downey,192126,Malibu
11,Trump,Trump Organization,254702,"New York, NY"
14,IngrahamAngle,Laura Ingraham,1664852,DC
16,TeamTrump,Official Team Trump,742514,USA
17,DRUDGE_REPORT,DRUDGE REPORT,1319753,US
19,LaraLeaTrump,Lara Trump,301998,New York City
20,seanhannity,Sean Hannity,2754923,NYC
22,CLewandowski_,Corey R. Lewandowski,285315,"Washington, DC"
23,AnnCoulter,Ann Coulter,1662294,Los Angeles/NYC
24,DiamondandSilk,Diamond and Silk¬Æ,382889,United States
25,KatrinaCampins,KATRINA CAMPINS,307559,Peace Within
26,KatrinaPierson,Katrina Pierson,339906,"Washington, DC"
27,MichaelCohen212,Michael Cohen,257489,New York
28,foxandfriends,FOX & friends,1012750,New York City
29,MELANIATRUMP,MELANIA TRUMP,892678,New York City
30,GeraldoRivera,Geraldo Rivera,157925,New York City
31,ericbolling,Eric Bolling,729649,NYC
32,MarkBurnettTV,Mark Burnett,193488,Los Angeles
33,garyplayer,Gary Player,359255,South Africa
34,VinceMcMahon,Vince McMahon,1789522,"Greenwich, Conn."
36,TrumpWaikiki,Trump Waikiki,48325,"Waikiki, Oahu"
37,TrumpDoral,Trump National Doral,56443,"Miami, Florida"
38,TrumpCharlotte,Trump Charlotte,38486,"Charlotte, NC"
39,TrumpLasVegas,Trump Vegas Hotel,99719,Las Vegas
40,TrumpChicago,Trump Hotel Chicago,67529,"Chicago, IL"
...,...,...,...,...
61,KellyannePolls,Kellyanne Conway,2584390,USAüá∫üá∏
62,Reince,Reince Priebus,934750,"Kenosha, WI and Washington, DC"
63,RealRomaDowney,Roma Downey,238918,"California, USA"
64,Trump,The Trump Organization,350208,"New York, NY"
67,IngrahamAngle,Laura Ingraham,2581320,DC
69,TeamTrump,Official Team Trump,956501,USA
72,DRUDGE_REPORT,DRUDGE REPORT,1403331,US
74,LaraLeaTrump,Lara Trump,492595,New York City
75,seanhannity,Sean Hannity,3928199,NYC
76,CLewandowski_,Corey R. Lewandowski,388884,"Washington, DC"
77,DiamondandSilk,Diamond and Silk¬Æ,1010717,United States
78,KatrinaCampins,KATRINA CAMPINS,273821,Peace Within
79,KatrinaPierson,Katrina Pierson,443386,"Washington, DC"
81,foxandfriends,FOX & friends,1335507,New York City
82,MELANIATRUMP,MELANIA TRUMP,1064983,New York City
83,GeraldoRivera,Geraldo Rivera,265232,New York City
84,ericbolling,Eric Bollingüá∫üá∏,1080806,NYC
87,MarkBurnettTV,Mark Burnett,219525,Los Angeles
88,garyplayer,Gary Player,393259,South Africa
89,VinceMcMahon,Vince McMahon,2197623,"Greenwich, Conn."
90,DanScavino,Dan Scavino,507539,"Washington, DC"
91,TrumpDoral,Trump National Doral,87502,"Miami, Florida"
92,TrumpCharlotte,Trump Charlotte,69155,"Charlotte, NC"
93,TrumpLasVegas,Trump Vegas Hotel,126917,Las Vegas
94,TrumpChicago,Trump Hotel Chicago,94208,"Chicago, IL"
95,TrumpGolfDC,Trump Washington DC,98794,"Sterling, VA"
96,TrumpGolfLA,Trump Los Angeles,81502,"Los Angeles, CA"
99,greta,Greta Van Susteren,1201546,Washington
101,piersmorgan,Piers Morgan,6535363,"London, Newick, LA."
103,IvankaTrump,Ivanka Trump,6159430,"Washington, DC"

In [10]:
# remove 4rth row which has a strange location
df2.drop([4], inplace=True, axis=0)
df2

,screen_name,name,followers_count,location
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC"
3,WhiteHouse,The White House,15327283,"Washington, D.C."
5,KellyannePolls,Kellyanne Conway,1664393,"Washington, DC"
6,Reince,Reince Priebus,941927,"Kenosha, WI and Washington, DC"
10,RealRomaDowney,Roma Downey,192126,Malibu
11,Trump,Trump Organization,254702,"New York, NY"
14,IngrahamAngle,Laura Ingraham,1664852,DC
16,TeamTrump,Official Team Trump,742514,USA
17,DRUDGE_REPORT,DRUDGE REPORT,1319753,US
19,LaraLeaTrump,Lara Trump,301998,New York City
20,seanhannity,Sean Hannity,2754923,NYC
22,CLewandowski_,Corey R. Lewandowski,285315,"Washington, DC"
23,AnnCoulter,Ann Coulter,1662294,Los Angeles/NYC
24,DiamondandSilk,Diamond and Silk¬Æ,382889,United States
25,KatrinaCampins,KATRINA CAMPINS,307559,Peace Within
26,KatrinaPierson,Katrina Pierson,339906,"Washington, DC"
27,MichaelCohen212,Michael Cohen,257489,New York
28,foxandfriends,FOX & friends,1012750,New York City
29,MELANIATRUMP,MELANIA TRUMP,892678,New York City
30,GeraldoRivera,Geraldo Rivera,157925,New York City
31,ericbolling,Eric Bolling,729649,NYC
32,MarkBurnettTV,Mark Burnett,193488,Los Angeles
33,garyplayer,Gary Player,359255,South Africa
34,VinceMcMahon,Vince McMahon,1789522,"Greenwich, Conn."
36,TrumpWaikiki,Trump Waikiki,48325,"Waikiki, Oahu"
37,TrumpDoral,Trump National Doral,56443,"Miami, Florida"
38,TrumpCharlotte,Trump Charlotte,38486,"Charlotte, NC"
39,TrumpLasVegas,Trump Vegas Hotel,99719,Las Vegas
40,TrumpChicago,Trump Hotel Chicago,67529,"Chicago, IL"
41,TrumpGolfDC,Trump Washington DC,56428,"Sterling, VA"
...,...,...,...,...
61,KellyannePolls,Kellyanne Conway,2584390,USAüá∫üá∏
62,Reince,Reince Priebus,934750,"Kenosha, WI and Washington, DC"
63,RealRomaDowney,Roma Downey,238918,"California, USA"
64,Trump,The Trump Organization,350208,"New York, NY"
67,IngrahamAngle,Laura Ingraham,2581320,DC
69,TeamTrump,Official Team Trump,956501,USA
72,DRUDGE_REPORT,DRUDGE REPORT,1403331,US
74,LaraLeaTrump,Lara Trump,492595,New York City
75,seanhannity,Sean Hannity,3928199,NYC
76,CLewandowski_,Corey R. Lewandowski,388884,"Washington, DC"
77,DiamondandSilk,Diamond and Silk¬Æ,1010717,United States
78,KatrinaCampins,KATRINA CAMPINS,273821,Peace Within
79,KatrinaPierson,Katrina Pierson,443386,"Washington, DC"
81,foxandfriends,FOX & friends,1335507,New York City
82,MELANIATRUMP,MELANIA TRUMP,1064983,New York City
83,GeraldoRivera,Geraldo Rivera,265232,New York City
84,ericbolling,Eric Bollingüá∫üá∏,1080806,NYC
87,MarkBurnettTV,Mark Burnett,219525,Los Angeles
88,garyplayer,Gary Player,393259,South Africa
89,VinceMcMahon,Vince McMahon,2197623,"Greenwich, Conn."
90,DanScavino,Dan Scavino,507539,"Washington, DC"
91,TrumpDoral,Trump National Doral,87502,"Miami, Florida"
92,TrumpCharlotte,Trump Charlotte,69155,"Charlotte, NC"
93,TrumpLasVegas,Trump Vegas Hotel,126917,Las Vegas
94,TrumpChicago,Trump Hotel Chicago,94208,"Chicago, IL"
95,TrumpGolfDC,Trump Washington DC,98794,"Sterling, VA"
96,TrumpGolfLA,Trump Los Angeles,81502,"Los Angeles, CA"
99,greta,Greta Van Susteren,1201546,Washington
101,piersmorgan,Piers Morgan,6535363,"London, Newick, LA."
103,IvankaTrump,Ivanka Trump,6159430,"Washington, DC"

In [11]:
# check the unique values in the column location
df2['location'].unique()

array(['Washington, DC', 'Washington, D.C.',
       'Kenosha, WI and Washington, DC', 'Malibu', 'New York, NY', 'DC',
       'USA', 'US', 'New York City', 'NYC', 'Los Angeles/NYC',
       'United States', 'Peace Within', 'New York',
       '                 NYC', 'Los Angeles', 'South Africa',
       'Greenwich, Conn.', 'Waikiki, Oahu', 'Miami, Florida',
       'Charlotte, NC', 'Las Vegas ', 'Chicago, IL', 'Sterling, VA',
       'Los Angeles, CA', 'Manhasset, NY', 'Washington',
       'London, Newick, LA. ', 'location', '1600 Pennsylvania Avenue ',
       'USAüá∫üá∏', 'California, USA', 'London, Newick, LA.'], dtype=object)

Washington appears in many different formats
the lines below replace all occurences of Washington to be the same
I have used the function replace of the pandas library (see http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html ) and a regular expression to indicate that any sequence starting by Wash and followed by any sequence of characters should be replaced by 'Washington, DC'. A good tutprial on regular expressions is at https://regexone.com/

In [12]:
df3=df2.replace(to_replace=r'Wash.+',value='Washington, DC', regex=True)
df3['location'].unique()

array(['Washington, DC', 'Kenosha, WI and Washington, DC', 'Malibu',
       'New York, NY', 'DC', 'USA', 'US', 'New York City', 'NYC',
       'Los Angeles/NYC', 'United States', 'Peace Within', 'New York',
       '                 NYC', 'Los Angeles', 'South Africa',
       'Greenwich, Conn.', 'Waikiki, Oahu', 'Miami, Florida',
       'Charlotte, NC', 'Las Vegas ', 'Chicago, IL', 'Sterling, VA',
       'Los Angeles, CA', 'Manhasset, NY', 'London, Newick, LA. ',
       'location', '1600 Pennsylvania Avenue ', 'USAüá∫üá∏',
       'California, USA', 'London, Newick, LA.'], dtype=object)

In [13]:
# note that df2 has not changed
df2['location'].unique()

array(['Washington, DC', 'Washington, D.C.',
       'Kenosha, WI and Washington, DC', 'Malibu', 'New York, NY', 'DC',
       'USA', 'US', 'New York City', 'NYC', 'Los Angeles/NYC',
       'United States', 'Peace Within', 'New York',
       '                 NYC', 'Los Angeles', 'South Africa',
       'Greenwich, Conn.', 'Waikiki, Oahu', 'Miami, Florida',
       'Charlotte, NC', 'Las Vegas ', 'Chicago, IL', 'Sterling, VA',
       'Los Angeles, CA', 'Manhasset, NY', 'Washington',
       'London, Newick, LA. ', 'location', '1600 Pennsylvania Avenue ',
       'USAüá∫üá∏', 'California, USA', 'London, Newick, LA.'], dtype=object)

In [14]:
# replace any DC at the beginning of the string with Washington, DC
# replace NYC preceded by any number of white spaces with New York, NY
# replace a string starting and finishing with US with USA
# replace USAüá∫üá∏ with USA
# replace New York City with New York, NY
# replace a string starting and finishing with New York with New York, NY
df4=df3.replace(regex={r'^DC': 'Washington, DC', '\s*NYC': 'New York, NY', '^US$':'USA', 'USAüá∫üá∏': 'USA', 'New York City': 'New York, NY', '^New York$':'New York, NY'})
df4['location'].unique()

array(['Washington, DC', 'Kenosha, WI and Washington, DC', 'Malibu',
       'New York, NY', 'USA', 'Los Angeles/New York, NY', 'United States',
       'Peace Within', 'Los Angeles', 'South Africa', 'Greenwich, Conn.',
       'Waikiki, Oahu', 'Miami, Florida', 'Charlotte, NC', 'Las Vegas ',
       'Chicago, IL', 'Sterling, VA', 'Los Angeles, CA', 'Manhasset, NY',
       'London, Newick, LA. ', 'location', '1600 Pennsylvania Avenue ',
       'California, USA', 'London, Newick, LA.'], dtype=object)

In [15]:
# Explore which are the entities with a certain location value (e.g. which ones have USA as location)
# (for each one of the rows in df4, [df4.location == 'USA'] returns true or false; only the rows corresponding to True are returned)
df4[df4.location == 'USA']

       screen_name                 name followers_count location
16       TeamTrump  Official Team Trump          742514      USA
17   DRUDGE_REPORT        DRUDGE REPORT         1319753      USA
61  KellyannePolls     Kellyanne Conway         2584390      USA
69       TeamTrump  Official Team Trump          956501      USA
72   DRUDGE_REPORT        DRUDGE REPORT         1403331      USA

In [16]:
# One location value is location, I want to see to what it corresponds
df4[df4.location == 'location']

    screen_name  name  followers_count  location
50  screen_name  name  followers_count  location

In [17]:
# I drop the line 50
df4.drop([50], inplace=True, axis=0)
df4

,screen_name,name,followers_count,location
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC"
3,WhiteHouse,The White House,15327283,"Washington, DC"
5,KellyannePolls,Kellyanne Conway,1664393,"Washington, DC"
6,Reince,Reince Priebus,941927,"Kenosha, WI and Washington, DC"
10,RealRomaDowney,Roma Downey,192126,Malibu
11,Trump,Trump Organization,254702,"New York, NY"
14,IngrahamAngle,Laura Ingraham,1664852,"Washington, DC"
16,TeamTrump,Official Team Trump,742514,USA
17,DRUDGE_REPORT,DRUDGE REPORT,1319753,USA
19,LaraLeaTrump,Lara Trump,301998,"New York, NY"
20,seanhannity,Sean Hannity,2754923,"New York, NY"
22,CLewandowski_,Corey R. Lewandowski,285315,"Washington, DC"
23,AnnCoulter,Ann Coulter,1662294,"Los Angeles/New York, NY"
24,DiamondandSilk,Diamond and Silk¬Æ,382889,United States
25,KatrinaCampins,KATRINA CAMPINS,307559,Peace Within
26,KatrinaPierson,Katrina Pierson,339906,"Washington, DC"
27,MichaelCohen212,Michael Cohen,257489,"New York, NY"
28,foxandfriends,FOX & friends,1012750,"New York, NY"
29,MELANIATRUMP,MELANIA TRUMP,892678,"New York, NY"
30,GeraldoRivera,Geraldo Rivera,157925,"New York, NY"
31,ericbolling,Eric Bolling,729649,"New York, NY"
32,MarkBurnettTV,Mark Burnett,193488,Los Angeles
33,garyplayer,Gary Player,359255,South Africa
34,VinceMcMahon,Vince McMahon,1789522,"Greenwich, Conn."
36,TrumpWaikiki,Trump Waikiki,48325,"Waikiki, Oahu"
37,TrumpDoral,Trump National Doral,56443,"Miami, Florida"
38,TrumpCharlotte,Trump Charlotte,38486,"Charlotte, NC"
39,TrumpLasVegas,Trump Vegas Hotel,99719,Las Vegas
40,TrumpChicago,Trump Hotel Chicago,67529,"Chicago, IL"
41,TrumpGolfDC,"Trump Washington, DC",56428,"Sterling, VA"
...,...,...,...,...
61,KellyannePolls,Kellyanne Conway,2584390,USA
62,Reince,Reince Priebus,934750,"Kenosha, WI and Washington, DC"
63,RealRomaDowney,Roma Downey,238918,"California, USA"
64,Trump,The Trump Organization,350208,"New York, NY"
67,IngrahamAngle,Laura Ingraham,2581320,"Washington, DC"
69,TeamTrump,Official Team Trump,956501,USA
72,DRUDGE_REPORT,DRUDGE REPORT,1403331,USA
74,LaraLeaTrump,Lara Trump,492595,"New York, NY"
75,seanhannity,Sean Hannity,3928199,"New York, NY"
76,CLewandowski_,Corey R. Lewandowski,388884,"Washington, DC"
77,DiamondandSilk,Diamond and Silk¬Æ,1010717,United States
78,KatrinaCampins,KATRINA CAMPINS,273821,Peace Within
79,KatrinaPierson,Katrina Pierson,443386,"Washington, DC"
81,foxandfriends,FOX & friends,1335507,"New York, NY"
82,MELANIATRUMP,MELANIA TRUMP,1064983,"New York, NY"
83,GeraldoRivera,Geraldo Rivera,265232,"New York, NY"
84,ericbolling,Eric Bollingüá∫üá∏,1080806,"New York, NY"
87,MarkBurnettTV,Mark Burnett,219525,Los Angeles
88,garyplayer,Gary Player,393259,South Africa
89,VinceMcMahon,Vince McMahon,2197623,"Greenwich, Conn."
90,DanScavino,Dan Scavino,507539,"Washington, DC"
91,TrumpDoral,Trump National Doral,87502,"Miami, Florida"
92,TrumpCharlotte,Trump Charlotte,69155,"Charlotte, NC"
93,TrumpLasVegas,Trump Vegas Hotel,126917,Las Vegas
94,TrumpChicago,Trump Hotel Chicago,94208,"Chicago, IL"
95,TrumpGolfDC,"Trump Washington, DC",98794,"Sterling, VA"
96,TrumpGolfLA,Trump Los Angeles,81502,"Los Angeles, CA"
99,greta,Greta Van Susteren,1201546,"Washington, DC"
101,piersmorgan,Piers Morgan,6535363,"London, Newick, LA."
103,IvankaTrump,Ivanka Trump,6159430,"Washington, DC"

In [18]:
# Now I want to eliminate the double locations
# From the table above I see that Reince Priebus has two locations but he also appears twice so I assign to 
# one occurence Kenosha, WI and to the other one Washington, DC
#
# in the column 'location' on line 6 assign 'Kenosha, WI'
df4['location'][6] = 'Kenosha, WI'
# in the column 'location' on line 62 assign Washington, DC'
df4['location'][62] = 'Washington, DC'
df4

,screen_name,name,followers_count,location
0,TuckerCarlson,Tucker Carlson,1064787,"Washington, DC"
3,WhiteHouse,The White House,15327283,"Washington, DC"
5,KellyannePolls,Kellyanne Conway,1664393,"Washington, DC"
6,Reince,Reince Priebus,941927,"Kenosha, WI"
10,RealRomaDowney,Roma Downey,192126,Malibu
11,Trump,Trump Organization,254702,"New York, NY"
14,IngrahamAngle,Laura Ingraham,1664852,"Washington, DC"
16,TeamTrump,Official Team Trump,742514,USA
17,DRUDGE_REPORT,DRUDGE REPORT,1319753,USA
19,LaraLeaTrump,Lara Trump,301998,"New York, NY"
20,seanhannity,Sean Hannity,2754923,"New York, NY"
22,CLewandowski_,Corey R. Lewandowski,285315,"Washington, DC"
23,AnnCoulter,Ann Coulter,1662294,"Los Angeles/New York, NY"
24,DiamondandSilk,Diamond and Silk¬Æ,382889,United States
25,KatrinaCampins,KATRINA CAMPINS,307559,Peace Within
26,KatrinaPierson,Katrina Pierson,339906,"Washington, DC"
27,MichaelCohen212,Michael Cohen,257489,"New York, NY"
28,foxandfriends,FOX & friends,1012750,"New York, NY"
29,MELANIATRUMP,MELANIA TRUMP,892678,"New York, NY"
30,GeraldoRivera,Geraldo Rivera,157925,"New York, NY"
31,ericbolling,Eric Bolling,729649,"New York, NY"
32,MarkBurnettTV,Mark Burnett,193488,Los Angeles
33,garyplayer,Gary Player,359255,South Africa
34,VinceMcMahon,Vince McMahon,1789522,"Greenwich, Conn."
36,TrumpWaikiki,Trump Waikiki,48325,"Waikiki, Oahu"
37,TrumpDoral,Trump National Doral,56443,"Miami, Florida"
38,TrumpCharlotte,Trump Charlotte,38486,"Charlotte, NC"
39,TrumpLasVegas,Trump Vegas Hotel,99719,Las Vegas
40,TrumpChicago,Trump Hotel Chicago,67529,"Chicago, IL"
41,TrumpGolfDC,"Trump Washington, DC",56428,"Sterling, VA"
...,...,...,...,...
61,KellyannePolls,Kellyanne Conway,2584390,USA
62,Reince,Reince Priebus,934750,"Washington, DC"
63,RealRomaDowney,Roma Downey,238918,"California, USA"
64,Trump,The Trump Organization,350208,"New York, NY"
67,IngrahamAngle,Laura Ingraham,2581320,"Washington, DC"
69,TeamTrump,Official Team Trump,956501,USA
72,DRUDGE_REPORT,DRUDGE REPORT,1403331,USA
74,LaraLeaTrump,Lara Trump,492595,"New York, NY"
75,seanhannity,Sean Hannity,3928199,"New York, NY"
76,CLewandowski_,Corey R. Lewandowski,388884,"Washington, DC"
77,DiamondandSilk,Diamond and Silk¬Æ,1010717,United States
78,KatrinaCampins,KATRINA CAMPINS,273821,Peace Within
79,KatrinaPierson,Katrina Pierson,443386,"Washington, DC"
81,foxandfriends,FOX & friends,1335507,"New York, NY"
82,MELANIATRUMP,MELANIA TRUMP,1064983,"New York, NY"
83,GeraldoRivera,Geraldo Rivera,265232,"New York, NY"
84,ericbolling,Eric Bollingüá∫üá∏,1080806,"New York, NY"
87,MarkBurnettTV,Mark Burnett,219525,Los Angeles
88,garyplayer,Gary Player,393259,South Africa
89,VinceMcMahon,Vince McMahon,2197623,"Greenwich, Conn."
90,DanScavino,Dan Scavino,507539,"Washington, DC"
91,TrumpDoral,Trump National Doral,87502,"Miami, Florida"
92,TrumpCharlotte,Trump Charlotte,69155,"Charlotte, NC"
93,TrumpLasVegas,Trump Vegas Hotel,126917,Las Vegas
94,TrumpChicago,Trump Hotel Chicago,94208,"Chicago, IL"
95,TrumpGolfDC,"Trump Washington, DC",98794,"Sterling, VA"
96,TrumpGolfLA,Trump Los Angeles,81502,"Los Angeles, CA"
99,greta,Greta Van Susteren,1201546,"Washington, DC"
101,piersmorgan,Piers Morgan,6535363,"London, Newick, LA."
103,IvankaTrump,Ivanka Trump,6159430,"Washington, DC"

In [19]:
# Ann Coulter also has a double location so I check whether she also appears twice (she does not)
df4[df4.name == 'Ann Coulter']

   screen_name         name followers_count                  location
23  AnnCoulter  Ann Coulter         1662294  Los Angeles/New York, NY

In [20]:
# I just keep Los Angeles
df4['location'][23] = 'Los Angeles, CA'
df4['location'].unique()

array(['Washington, DC', 'Kenosha, WI', 'Malibu', 'New York, NY', 'USA',
       'Los Angeles, CA', 'United States', 'Peace Within', 'Los Angeles',
       'South Africa', 'Greenwich, Conn.', 'Waikiki, Oahu',
       'Miami, Florida', 'Charlotte, NC', 'Las Vegas ', 'Chicago, IL',
       'Sterling, VA', 'Manhasset, NY', 'London, Newick, LA. ',
       '1600 Pennsylvania Avenue ', 'California, USA',
       'London, Newick, LA.'], dtype=object)

In [21]:
# look for all entities with location equal 'London, Newick, LA. ' or 'London, Newick, LA.'
df4[(df4.location == 'London, Newick, LA. ') | (df4.location == 'London, Newick, LA.')]

     screen_name          name followers_count              location
46   piersmorgan  Piers Morgan         6035181  London, Newick, LA.
101  piersmorgan  Piers Morgan         6535363   London, Newick, LA.

In [22]:
# make one in London and one in LA
df4['location'][46] = 'London, UK'
df4['location'][101] = 'Los Angeles, CA'
df4['location'].unique()

array(['Washington, DC', 'Kenosha, WI', 'Malibu', 'New York, NY', 'USA',
       'Los Angeles, CA', 'United States', 'Peace Within', 'Los Angeles',
       'South Africa', 'Greenwich, Conn.', 'Waikiki, Oahu',
       'Miami, Florida', 'Charlotte, NC', 'Las Vegas ', 'Chicago, IL',
       'Sterling, VA', 'Manhasset, NY', 'London, UK',
       '1600 Pennsylvania Avenue ', 'California, USA'], dtype=object)

In [23]:
# Last few changes
df5=df4.replace(regex={r'United States': 'USA', '^Los Angeles$': 'Los Angeles, CA', '1600 Pennsylvania Avenue ': '1600 Pennsylvania Avenue, Washington, DC'})
df5['location'].unique()

array(['Washington, DC', 'Kenosha, WI', 'Malibu', 'New York, NY', 'USA',
       'Los Angeles, CA', 'Peace Within', 'South Africa',
       'Greenwich, Conn.', 'Waikiki, Oahu', 'Miami, Florida',
       'Charlotte, NC', 'Las Vegas ', 'Chicago, IL', 'Sterling, VA',
       'Manhasset, NY', 'London, UK',
       '1600 Pennsylvania Avenue, Washington, DC', 'California, USA'],
      dtype=object)

In [24]:
df5.to_csv('cleanDataFromTweeter.txt')

#### Do the remaining exercises in the CleaningDataExercises notebook